CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE SCHEMA IF NOT EXISTS private;
REVOKE ALL ON SCHEMA private FROM PUBLIC, anon, authenticated;

CREATE TYPE public.account_role AS ENUM ('client', 'specialist', 'venue');
CREATE TYPE public.provider_type AS ENUM ('specialist', 'venue');
CREATE TYPE public.booking_kind AS ENUM ('appointment', 'stay');
CREATE TYPE public.booking_status AS ENUM ('pending', 'confirmed', 'rejected', 'cancelled', 'completed');
CREATE TYPE public.conversation_kind AS ENUM ('direct', 'category');
CREATE TYPE public.report_status AS ENUM ('open', 'reviewing', 'resolved', 'dismissed');

CREATE TABLE public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name TEXT NOT NULL DEFAULT '',
  avatar_url TEXT,
  role public.account_role,
  city TEXT,
  is_banned BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE private.profile_private (
  profile_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  phone TEXT,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE private.admin_users (
  user_id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  granted_by UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE private.device_tokens (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  token TEXT NOT NULL UNIQUE,
  platform TEXT NOT NULL CHECK (platform IN ('android', 'ios')),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE private.ai_usage (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  window_started_at TIMESTAMPTZ NOT NULL,
  request_count INTEGER NOT NULL DEFAULT 0,
  PRIMARY KEY (user_id, window_started_at)
);

CREATE TABLE public.service_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  slug TEXT NOT NULL,
  provider_type public.provider_type NOT NULL,
  name TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT 'grid',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (provider_type, slug)
);

CREATE TABLE public.services (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  category_id BIGINT NOT NULL REFERENCES public.service_categories(id) ON DELETE CASCADE,
  slug TEXT NOT NULL,
  name TEXT NOT NULL,
  icon TEXT NOT NULL DEFAULT 'map-pin',
  sort_order INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  UNIQUE (category_id, slug)
);

CREATE TABLE public.specialist_profiles (
  id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  bio TEXT,
  experience_years INTEGER NOT NULL DEFAULT 0 CHECK (experience_years >= 0),
  price_start INTEGER NOT NULL DEFAULT 0 CHECK (price_start >= 0),
  service_area TEXT CHECK (service_area IN ('akshi', 'koktuma', 'usharal')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.venue_profiles (
  id UUID PRIMARY KEY REFERENCES public.profiles(id) ON DELETE CASCADE,
  description TEXT,
  address TEXT,
  capacity INTEGER NOT NULL DEFAULT 0 CHECK (capacity >= 0),
  location_zone TEXT CHECK (location_zone IN ('akshi', 'koktuma', 'usharal')),
  price_from INTEGER NOT NULL DEFAULT 0 CHECK (price_from >= 0),
  distance_to_beach_m INTEGER CHECK (distance_to_beach_m >= 0),
  has_wifi BOOLEAN NOT NULL DEFAULT FALSE,
  has_parking BOOLEAN NOT NULL DEFAULT FALSE,
  has_meals BOOLEAN NOT NULL DEFAULT FALSE,
  family_friendly BOOLEAN NOT NULL DEFAULT FALSE,
  pet_friendly BOOLEAN NOT NULL DEFAULT FALSE,
  season_open DATE,
  season_close DATE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE private.venue_locations (
  provider_id UUID PRIMARY KEY REFERENCES public.venue_profiles(id) ON DELETE CASCADE,
  latitude DOUBLE PRECISION NOT NULL CHECK (latitude BETWEEN -90 AND 90),
  longitude DOUBLE PRECISION NOT NULL CHECK (longitude BETWEEN -180 AND 180),
  is_public BOOLEAN NOT NULL DEFAULT FALSE,
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.provider_services (
  provider_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  service_id BIGINT NOT NULL REFERENCES public.services(id) ON DELETE CASCADE,
  price_from INTEGER CHECK (price_from >= 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (provider_id, service_id)
);

CREATE TABLE public.portfolio_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  owner_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  file_url TEXT NOT NULL,
  thumbnail_url TEXT,
  file_type TEXT NOT NULL DEFAULT 'image' CHECK (file_type IN ('image', 'video')),
  in_feed BOOLEAN NOT NULL DEFAULT FALSE,
  is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
  is_hero BOOLEAN NOT NULL DEFAULT FALSE,
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.bookings (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  provider_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  service_id BIGINT REFERENCES public.services(id) ON DELETE SET NULL,
  kind public.booking_kind NOT NULL,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ,
  guest_count INTEGER CHECK (guest_count > 0),
  status public.booking_status NOT NULL DEFAULT 'pending',
  message TEXT CHECK (char_length(message) <= 2000),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (client_id <> provider_id),
  CHECK (
    (kind = 'appointment' AND service_id IS NOT NULL AND ends_at IS NULL AND guest_count IS NULL)
    OR
    (kind = 'stay' AND ends_at IS NOT NULL AND ends_at > starts_at AND guest_count IS NOT NULL)
  )
);

CREATE TABLE public.provider_blocks (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  provider_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  starts_at TIMESTAMPTZ NOT NULL,
  ends_at TIMESTAMPTZ NOT NULL,
  reason TEXT CHECK (char_length(reason) <= 500),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK (ends_at > starts_at)
);

CREATE TABLE public.reviews (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  booking_id UUID NOT NULL UNIQUE REFERENCES public.bookings(id) ON DELETE CASCADE,
  client_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  rating INTEGER NOT NULL CHECK (rating BETWEEN 1 AND 5),
  comment TEXT CHECK (char_length(comment) <= 4000),
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.favorites (
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (user_id, target_id),
  CHECK (user_id <> target_id)
);

CREATE TABLE public.conversations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  kind public.conversation_kind NOT NULL,
  category_id BIGINT REFERENCES public.service_categories(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CHECK ((kind = 'category') = (category_id IS NOT NULL))
);

CREATE TABLE public.conversation_members (
  conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  last_read_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (conversation_id, user_id)
);

CREATE TABLE public.messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id UUID NOT NULL REFERENCES public.conversations(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL CHECK (char_length(content) BETWEEN 1 AND 4000),
  is_hidden BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.notifications (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  data JSONB NOT NULL DEFAULT '{}'::JSONB,
  is_read BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.blocks (
  blocker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  blocked_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  PRIMARY KEY (blocker_id, blocked_id),
  CHECK (blocker_id <> blocked_id)
);

CREATE TABLE public.reports (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  reporter_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  target_type TEXT NOT NULL CHECK (target_type IN ('profile', 'message', 'review', 'portfolio')),
  target_id UUID NOT NULL,
  reason TEXT NOT NULL CHECK (char_length(reason) BETWEEN 3 AND 1000),
  status public.report_status NOT NULL DEFAULT 'open',
  resolution_note TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  actor_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  action TEXT NOT NULL,
  target_type TEXT NOT NULL,
  target_id TEXT NOT NULL,
  metadata JSONB NOT NULL DEFAULT '{}'::JSONB,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_provider_services_service ON public.provider_services(service_id, provider_id);
CREATE INDEX idx_bookings_client ON public.bookings(client_id, created_at DESC);
CREATE INDEX idx_bookings_provider ON public.bookings(provider_id, created_at DESC);
CREATE INDEX idx_provider_blocks_range ON public.provider_blocks(provider_id, starts_at, ends_at);
CREATE INDEX idx_messages_conversation ON public.messages(conversation_id, created_at DESC);
CREATE INDEX idx_notifications_user ON public.notifications(user_id, created_at DESC);
CREATE INDEX idx_reports_status ON public.reports(status, created_at);
CREATE INDEX idx_portfolio_feed ON public.portfolio_items(in_feed, is_hidden, created_at DESC);

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  SELECT EXISTS (SELECT 1 FROM private.admin_users WHERE user_id = auth.uid());
$$;

CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, private, pg_temp
AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, city)
  VALUES (
    NEW.id,
    COALESCE(NULLIF(BTRIM(NEW.raw_user_meta_data->>'full_name'), ''), 'Пользователь'),
    NULLIF(BTRIM(NEW.raw_user_meta_data->>'city'), '')
  );
  INSERT INTO private.profile_private (profile_id) VALUES (NEW.id);
  RETURN NEW;
END;
$$;

CREATE TRIGGER on_auth_user_created
AFTER INSERT ON auth.users
FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

CREATE OR REPLACE FUNCTION public.touch_updated_at()
RETURNS TRIGGER LANGUAGE plpgsql SET search_path = public, pg_temp AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

CREATE TRIGGER profiles_touch BEFORE UPDATE ON public.profiles
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER specialists_touch BEFORE UPDATE ON public.specialist_profiles
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER venues_touch BEFORE UPDATE ON public.venue_profiles
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER bookings_touch BEFORE UPDATE ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();
CREATE TRIGGER reports_touch BEFORE UPDATE ON public.reports
FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

CREATE OR REPLACE FUNCTION public.create_appointment(
  p_provider_id UUID,
  p_service_id BIGINT,
  p_starts_at TIMESTAMPTZ,
  p_message TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_id UUID;
BEGIN
  IF auth.uid() IS NULL OR p_starts_at <= NOW() THEN
    RAISE EXCEPTION 'invalid appointment';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_provider_id::TEXT, 0));
  IF NOT EXISTS (
    SELECT 1 FROM public.provider_services
    WHERE provider_id = p_provider_id AND service_id = p_service_id
  ) THEN RAISE EXCEPTION 'provider does not offer service'; END IF;
  IF EXISTS (
    SELECT 1 FROM public.provider_blocks
    WHERE provider_id = p_provider_id
      AND starts_at < p_starts_at + INTERVAL '1 hour'
      AND ends_at > p_starts_at
  ) THEN RAISE EXCEPTION 'slot is unavailable'; END IF;
  IF EXISTS (
    SELECT 1 FROM public.bookings
    WHERE provider_id = p_provider_id
      AND status IN ('pending', 'confirmed')
      AND starts_at < p_starts_at + INTERVAL '1 hour'
      AND COALESCE(ends_at, starts_at + INTERVAL '1 hour') > p_starts_at
  ) THEN RAISE EXCEPTION 'slot is unavailable'; END IF;
  INSERT INTO public.bookings(client_id, provider_id, service_id, kind, starts_at, message)
  VALUES (auth.uid(), p_provider_id, p_service_id, 'appointment', p_starts_at, NULLIF(BTRIM(p_message), ''))
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.create_stay_booking(
  p_venue_id UUID,
  p_starts_at TIMESTAMPTZ,
  p_ends_at TIMESTAMPTZ,
  p_guest_count INTEGER,
  p_message TEXT DEFAULT NULL
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_id UUID;
BEGIN
  IF auth.uid() IS NULL OR p_starts_at < CURRENT_DATE OR p_ends_at <= p_starts_at OR p_guest_count <= 0 THEN
    RAISE EXCEPTION 'invalid stay booking';
  END IF;
  PERFORM pg_advisory_xact_lock(hashtextextended(p_venue_id::TEXT, 0));
  IF NOT EXISTS (
    SELECT 1 FROM public.venue_profiles
    WHERE id = p_venue_id AND (capacity = 0 OR capacity >= p_guest_count)
  ) THEN
    RAISE EXCEPTION 'venue not found';
  END IF;
  IF EXISTS (
    SELECT 1 FROM public.provider_blocks
    WHERE provider_id = p_venue_id
      AND starts_at < p_ends_at AND ends_at > p_starts_at
  ) THEN RAISE EXCEPTION 'dates are unavailable'; END IF;
  IF EXISTS (
    SELECT 1 FROM public.bookings
    WHERE provider_id = p_venue_id
      AND status IN ('pending', 'confirmed')
      AND starts_at < p_ends_at
      AND COALESCE(ends_at, starts_at + INTERVAL '1 hour') > p_starts_at
  ) THEN RAISE EXCEPTION 'dates are unavailable'; END IF;
  INSERT INTO public.bookings(client_id, provider_id, kind, starts_at, ends_at, guest_count, message)
  VALUES (auth.uid(), p_venue_id, 'stay', p_starts_at, p_ends_at, p_guest_count, NULLIF(BTRIM(p_message), ''))
  RETURNING id INTO v_id;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.transition_booking(p_booking_id UUID, p_status public.booking_status)
RETURNS public.bookings
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_booking public.bookings;
BEGIN
  SELECT * INTO v_booking FROM public.bookings WHERE id = p_booking_id FOR UPDATE;
  IF NOT FOUND THEN RAISE EXCEPTION 'booking not found'; END IF;
  IF public.is_admin() THEN
    INSERT INTO public.audit_logs(actor_id, action, target_type, target_id, metadata)
    VALUES (auth.uid(), 'booking_override', 'booking', p_booking_id::TEXT, jsonb_build_object('from', v_booking.status, 'to', p_status));
  ELSIF auth.uid() = v_booking.client_id THEN
    IF p_status <> 'cancelled' OR v_booking.status NOT IN ('pending', 'confirmed') THEN
      RAISE EXCEPTION 'transition not allowed';
    END IF;
  ELSIF auth.uid() = v_booking.provider_id THEN
    IF NOT (
      (v_booking.status = 'pending' AND p_status IN ('confirmed', 'rejected'))
      OR (v_booking.status = 'confirmed' AND p_status = 'completed' AND v_booking.starts_at <= NOW())
    ) THEN RAISE EXCEPTION 'transition not allowed'; END IF;
  ELSE
    RAISE EXCEPTION 'not allowed';
  END IF;
  UPDATE public.bookings SET status = p_status WHERE id = p_booking_id RETURNING * INTO v_booking;
  RETURN v_booking;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_provider_unavailable_intervals(
  p_provider_id UUID,
  p_from TIMESTAMPTZ,
  p_to TIMESTAMPTZ
)
RETURNS TABLE(starts_at TIMESTAMPTZ, ends_at TIMESTAMPTZ)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT block.starts_at, block.ends_at
  FROM public.provider_blocks block
  WHERE auth.uid() IS NOT NULL
    AND block.provider_id = p_provider_id
    AND p_to > p_from
    AND p_to <= p_from + INTERVAL '370 days'
    AND block.starts_at < p_to AND block.ends_at > p_from
  UNION ALL
  SELECT booking.starts_at, COALESCE(booking.ends_at, booking.starts_at + INTERVAL '1 hour')
  FROM public.bookings booking
  WHERE auth.uid() IS NOT NULL
    AND booking.provider_id = p_provider_id
    AND booking.status IN ('pending', 'confirmed')
    AND p_to > p_from
    AND p_to <= p_from + INTERVAL '370 days'
    AND booking.starts_at < p_to
    AND COALESCE(booking.ends_at, booking.starts_at + INTERVAL '1 hour') > p_from;
$$;

CREATE OR REPLACE FUNCTION public.admin_set_user_banned(p_user_id UUID, p_banned BOOLEAN)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF NOT public.is_admin() OR p_user_id = auth.uid() THEN RAISE EXCEPTION 'not allowed'; END IF;
  UPDATE public.profiles SET is_banned = p_banned WHERE id = p_user_id;
  IF NOT FOUND THEN RAISE EXCEPTION 'user not found'; END IF;
  INSERT INTO public.audit_logs(actor_id, action, target_type, target_id, metadata)
  VALUES (auth.uid(), 'set_user_banned', 'profile', p_user_id::TEXT, jsonb_build_object('is_banned', p_banned));
END;
$$;

CREATE OR REPLACE FUNCTION public.set_initial_role(p_role public.account_role, p_city TEXT DEFAULT NULL)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'not_authenticated'; END IF;
  UPDATE public.profiles
  SET role = p_role, city = COALESCE(NULLIF(BTRIM(p_city), ''), city)
  WHERE id = auth.uid() AND role IS NULL;
  IF NOT FOUND THEN RAISE EXCEPTION 'role_already_selected'; END IF;

  IF p_role = 'specialist' THEN
    INSERT INTO public.specialist_profiles(id) VALUES (auth.uid()) ON CONFLICT DO NOTHING;
  ELSIF p_role = 'venue' THEN
    INSERT INTO public.venue_profiles(id) VALUES (auth.uid()) ON CONFLICT DO NOTHING;
  END IF;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_or_create_direct_conversation(p_partner_id UUID)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_id UUID;
BEGIN
  IF auth.uid() IS NULL OR p_partner_id = auth.uid() THEN RAISE EXCEPTION 'invalid partner'; END IF;
  PERFORM pg_advisory_xact_lock(
    hashtextextended(LEAST(auth.uid()::TEXT, p_partner_id::TEXT) || GREATEST(auth.uid()::TEXT, p_partner_id::TEXT), 0)
  );
  IF EXISTS (
    SELECT 1 FROM public.blocks
    WHERE (blocker_id = auth.uid() AND blocked_id = p_partner_id)
       OR (blocker_id = p_partner_id AND blocked_id = auth.uid())
  ) THEN RAISE EXCEPTION 'conversation is blocked'; END IF;
  SELECT c.id INTO v_id
  FROM public.conversations c
  JOIN public.conversation_members mine ON mine.conversation_id = c.id AND mine.user_id = auth.uid()
  JOIN public.conversation_members partner ON partner.conversation_id = c.id AND partner.user_id = p_partner_id
  WHERE c.kind = 'direct'
    AND (SELECT COUNT(*) FROM public.conversation_members cm WHERE cm.conversation_id = c.id) = 2
  LIMIT 1;
  IF v_id IS NULL THEN
    INSERT INTO public.conversations(kind) VALUES ('direct') RETURNING id INTO v_id;
    INSERT INTO public.conversation_members(conversation_id, user_id)
    VALUES (v_id, auth.uid()), (v_id, p_partner_id);
  END IF;
  RETURN v_id;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_my_chats()
RETURNS TABLE (
  conversation_id UUID,
  partner_id UUID,
  full_name TEXT,
  avatar_url TEXT,
  last_message TEXT,
  last_message_time TIMESTAMPTZ
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT
    c.id,
    partner.user_id,
    p.full_name,
    p.avatar_url,
    last_message.content,
    last_message.created_at
  FROM public.conversations c
  JOIN public.conversation_members mine ON mine.conversation_id = c.id AND mine.user_id = auth.uid()
  JOIN public.conversation_members partner ON partner.conversation_id = c.id AND partner.user_id <> auth.uid()
  JOIN public.profiles p ON p.id = partner.user_id
  LEFT JOIN LATERAL (
    SELECT m.content, m.created_at FROM public.messages m
    WHERE m.conversation_id = c.id AND NOT m.is_hidden
    ORDER BY m.created_at DESC LIMIT 1
  ) last_message ON TRUE
  WHERE c.kind = 'direct'
  ORDER BY last_message.created_at DESC NULLS LAST;
$$;

CREATE OR REPLACE FUNCTION public.mark_conversation_read(p_conversation_id UUID)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.conversations c
    WHERE c.id = p_conversation_id
      AND (
        c.kind = 'category'
        OR EXISTS (
          SELECT 1 FROM public.conversation_members cm
          WHERE cm.conversation_id = c.id AND cm.user_id = auth.uid()
        )
      )
  ) THEN RAISE EXCEPTION 'conversation_not_accessible'; END IF;

  INSERT INTO public.conversation_members(conversation_id, user_id, last_read_at)
  VALUES (p_conversation_id, auth.uid(), NOW())
  ON CONFLICT (conversation_id, user_id)
  DO UPDATE SET last_read_at = EXCLUDED.last_read_at;
END;
$$;

CREATE OR REPLACE FUNCTION public.register_device_token(p_token TEXT, p_platform TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL OR p_platform NOT IN ('android', 'ios') OR BTRIM(p_token) = '' THEN
    RAISE EXCEPTION 'invalid token';
  END IF;
  INSERT INTO private.device_tokens(user_id, token, platform)
  VALUES (auth.uid(), p_token, p_platform)
  ON CONFLICT (token) DO UPDATE SET user_id = EXCLUDED.user_id, platform = EXCLUDED.platform, updated_at = NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.unregister_device_token(p_token TEXT)
RETURNS VOID
LANGUAGE SQL
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  DELETE FROM private.device_tokens
  WHERE user_id = auth.uid() AND token = p_token;
$$;

CREATE OR REPLACE FUNCTION public.get_my_private_profile()
RETURNS TABLE(phone TEXT)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  SELECT pp.phone FROM private.profile_private pp WHERE pp.profile_id = auth.uid();
$$;

CREATE OR REPLACE FUNCTION public.update_my_private_profile(p_phone TEXT)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL THEN RAISE EXCEPTION 'not authenticated'; END IF;
  INSERT INTO private.profile_private(profile_id, phone, updated_at)
  VALUES (auth.uid(), NULLIF(BTRIM(p_phone), ''), NOW())
  ON CONFLICT (profile_id) DO UPDATE SET phone = EXCLUDED.phone, updated_at = NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.get_venue_location(p_provider_id UUID)
RETURNS TABLE(latitude DOUBLE PRECISION, longitude DOUBLE PRECISION, is_public BOOLEAN)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  SELECT location.latitude, location.longitude, location.is_public
  FROM private.venue_locations location
  WHERE location.provider_id = p_provider_id
    AND (location.is_public OR p_provider_id = auth.uid() OR public.is_admin());
$$;

CREATE OR REPLACE FUNCTION public.update_my_venue_location(
  p_latitude DOUBLE PRECISION,
  p_longitude DOUBLE PRECISION,
  p_is_public BOOLEAN
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
BEGIN
  IF auth.uid() IS NULL OR NOT EXISTS (
    SELECT 1 FROM public.venue_profiles WHERE id = auth.uid()
  ) THEN RAISE EXCEPTION 'venue_required'; END IF;
  IF p_latitude NOT BETWEEN -90 AND 90 OR p_longitude NOT BETWEEN -180 AND 180 THEN
    RAISE EXCEPTION 'invalid_coordinates';
  END IF;
  INSERT INTO private.venue_locations(provider_id, latitude, longitude, is_public, updated_at)
  VALUES (auth.uid(), p_latitude, p_longitude, p_is_public, NOW())
  ON CONFLICT (provider_id) DO UPDATE SET
    latitude = EXCLUDED.latitude,
    longitude = EXCLUDED.longitude,
    is_public = EXCLUDED.is_public,
    updated_at = NOW();
END;
$$;

CREATE OR REPLACE FUNCTION public.consume_ai_quota()
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
DECLARE v_window TIMESTAMPTZ := date_trunc('hour', NOW()); v_count INTEGER;
BEGIN
  IF auth.uid() IS NULL THEN RETURN FALSE; END IF;
  INSERT INTO private.ai_usage(user_id, window_started_at, request_count)
  VALUES (auth.uid(), v_window, 1)
  ON CONFLICT (user_id, window_started_at)
  DO UPDATE SET request_count = private.ai_usage.request_count + 1
  RETURNING request_count INTO v_count;
  RETURN v_count <= 20;
END;
$$;

CREATE OR REPLACE FUNCTION public.get_push_tokens(p_user_id UUID)
RETURNS TABLE(token TEXT, platform TEXT)
LANGUAGE SQL
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  SELECT dt.token, dt.platform
  FROM private.device_tokens dt
  WHERE auth.role() = 'service_role' AND dt.user_id = p_user_id;
$$;

CREATE OR REPLACE FUNCTION public.notify_booking_change()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_user UUID; v_title TEXT; v_body TEXT;
BEGIN
  IF TG_OP = 'INSERT' THEN
    v_user := NEW.provider_id; v_title := 'Новая заявка'; v_body := 'У вас новая заявка на бронирование.';
  ELSIF NEW.status IS DISTINCT FROM OLD.status THEN
    v_user := NEW.client_id; v_title := 'Статус бронирования изменён'; v_body := 'Новый статус: ' || NEW.status::TEXT;
  ELSE RETURN NEW; END IF;
  INSERT INTO public.notifications(user_id, title, body, data)
  VALUES (v_user, v_title, v_body, jsonb_build_object('bookingId', NEW.id, 'status', NEW.status));
  RETURN NEW;
END;
$$;

CREATE TRIGGER booking_notification
AFTER INSERT OR UPDATE OF status ON public.bookings
FOR EACH ROW EXECUTE FUNCTION public.notify_booking_change();

CREATE OR REPLACE VIEW public.provider_search_view
WITH (security_invoker = true)
AS
SELECT
  p.id,
  p.full_name,
  p.avatar_url,
  p.city,
  p.role::TEXT AS provider_type,
  c.slug AS category_slug,
  c.name AS category_name,
  s.slug AS service_slug,
  s.id AS service_id,
  s.name AS service_name,
  COALESCE(ps.price_from, sp.price_start, vp.price_from, 0) AS price_from,
  sp.experience_years,
  sp.service_area,
  vp.capacity,
  vp.location_zone,
  NULL::DOUBLE PRECISION AS latitude,
  NULL::DOUBLE PRECISION AS longitude,
  vp.distance_to_beach_m,
  COALESCE(AVG(r.rating) FILTER (WHERE NOT r.is_hidden), 0)::NUMERIC(3,2) AS avg_rating,
  COUNT(r.id) FILTER (WHERE NOT r.is_hidden) AS review_count
FROM public.profiles p
JOIN public.provider_services ps ON ps.provider_id = p.id
JOIN public.services s ON s.id = ps.service_id AND s.is_active
JOIN public.service_categories c ON c.id = s.category_id AND c.is_active
LEFT JOIN public.specialist_profiles sp ON sp.id = p.id
LEFT JOIN public.venue_profiles vp ON vp.id = p.id
LEFT JOIN public.reviews r ON r.target_id = p.id
WHERE NOT p.is_banned
  AND NOT EXISTS (
    SELECT 1 FROM public.blocks b
    WHERE auth.uid() IS NOT NULL
      AND (
        (b.blocker_id = auth.uid() AND b.blocked_id = p.id)
        OR (b.blocker_id = p.id AND b.blocked_id = auth.uid())
      )
  )
GROUP BY p.id, c.slug, c.name, s.id, s.slug, s.name, ps.price_from, sp.price_start, sp.experience_years,
  sp.service_area, vp.price_from, vp.capacity, vp.location_zone, vp.distance_to_beach_m;

CREATE OR REPLACE FUNCTION public.search_providers(
  p_provider_type public.provider_type DEFAULT NULL,
  p_category_slug TEXT DEFAULT NULL,
  p_service_slug TEXT DEFAULT NULL,
  p_city TEXT DEFAULT NULL,
  p_max_price NUMERIC DEFAULT NULL,
  p_sort TEXT DEFAULT 'rating',
  p_latitude DOUBLE PRECISION DEFAULT NULL,
  p_longitude DOUBLE PRECISION DEFAULT NULL
)
RETURNS TABLE(
  id UUID,
  full_name TEXT,
  avatar_url TEXT,
  city TEXT,
  provider_type TEXT,
  category_slug TEXT,
  category_name TEXT,
  service_slug TEXT,
  service_id BIGINT,
  service_name TEXT,
  price_from NUMERIC,
  experience_years INTEGER,
  service_area TEXT,
  capacity INTEGER,
  location_zone TEXT,
  latitude DOUBLE PRECISION,
  longitude DOUBLE PRECISION,
  distance_to_beach_m INTEGER,
  avg_rating NUMERIC,
  review_count BIGINT,
  distance_km DOUBLE PRECISION
)
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = private, public, pg_temp
AS $$
  SELECT
    v.id, v.full_name, v.avatar_url, v.city, v.provider_type,
    v.category_slug, v.category_name, v.service_slug, v.service_id,
    v.service_name, v.price_from, v.experience_years, v.service_area, v.capacity, v.location_zone,
    location.latitude,
    location.longitude,
    v.distance_to_beach_m, v.avg_rating, v.review_count,
    CASE
      WHEN v.provider_type = 'venue'
        AND p_latitude IS NOT NULL AND p_longitude IS NOT NULL
        AND location.latitude IS NOT NULL AND location.longitude IS NOT NULL
      THEN 6371 * acos(LEAST(1, GREATEST(-1,
        cos(radians(p_latitude)) * cos(radians(location.latitude))
        * cos(radians(location.longitude) - radians(p_longitude))
        + sin(radians(p_latitude)) * sin(radians(location.latitude))
      )))
    END AS distance_km
  FROM public.provider_search_view v
  LEFT JOIN private.venue_locations location
    ON location.provider_id = v.id AND location.is_public AND v.provider_type = 'venue'
  WHERE (p_provider_type IS NULL OR v.provider_type = p_provider_type::TEXT)
    AND (p_category_slug IS NULL OR v.category_slug = p_category_slug)
    AND (p_service_slug IS NULL OR v.service_slug = p_service_slug)
    AND (p_city IS NULL OR v.city ILIKE '%' || p_city || '%')
    AND (p_max_price IS NULL OR v.price_from <= p_max_price)
  ORDER BY
    CASE WHEN p_sort = 'price' THEN v.price_from END ASC NULLS LAST,
    CASE WHEN p_sort = 'distance' THEN
      CASE
        WHEN v.provider_type = 'venue'
          AND p_latitude IS NOT NULL AND p_longitude IS NOT NULL
          AND location.latitude IS NOT NULL AND location.longitude IS NOT NULL
        THEN 6371 * acos(LEAST(1, GREATEST(-1,
          cos(radians(p_latitude)) * cos(radians(location.latitude))
          * cos(radians(location.longitude) - radians(p_longitude))
          + sin(radians(p_latitude)) * sin(radians(location.latitude))
        )))
      END
    END ASC NULLS LAST,
    v.avg_rating DESC,
    v.full_name ASC;
$$;

CREATE OR REPLACE FUNCTION public.is_conversation_member(p_conversation_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
  SELECT auth.uid() IS NOT NULL AND EXISTS (
    SELECT 1
    FROM public.conversation_members
    WHERE conversation_id = p_conversation_id AND user_id = auth.uid()
  );
$$;

CREATE OR REPLACE FUNCTION public.moderate_report(
  p_report_id UUID,
  p_action TEXT,
  p_note TEXT DEFAULT NULL
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE v_report public.reports%ROWTYPE;
BEGIN
  IF NOT public.is_admin() THEN RAISE EXCEPTION 'admin_required'; END IF;
  IF p_action NOT IN ('hide', 'dismiss') THEN RAISE EXCEPTION 'invalid_action'; END IF;

  SELECT * INTO v_report FROM public.reports WHERE id = p_report_id FOR UPDATE;
  IF NOT FOUND OR v_report.status <> 'open' THEN RAISE EXCEPTION 'report_not_open'; END IF;

  IF p_action = 'hide' THEN
    CASE v_report.target_type
      WHEN 'profile' THEN UPDATE public.profiles SET is_banned = TRUE WHERE id = v_report.target_id;
      WHEN 'message' THEN UPDATE public.messages SET is_hidden = TRUE WHERE id = v_report.target_id;
      WHEN 'review' THEN UPDATE public.reviews SET is_hidden = TRUE WHERE id = v_report.target_id;
      WHEN 'portfolio' THEN UPDATE public.portfolio_items SET is_hidden = TRUE WHERE id = v_report.target_id;
      ELSE RAISE EXCEPTION 'invalid_target_type';
    END CASE;
  END IF;

  UPDATE public.reports
  SET status = CASE WHEN p_action = 'hide' THEN 'resolved' ELSE 'dismissed' END,
      resolution_note = NULLIF(trim(p_note), ''),
      updated_at = NOW()
  WHERE id = p_report_id;

  INSERT INTO public.audit_logs(actor_id, action, target_type, target_id, metadata)
  VALUES (
    auth.uid(), 'moderate_report_' || p_action, v_report.target_type, v_report.target_id::TEXT,
    jsonb_build_object('report_id', p_report_id, 'note', p_note)
  );
END;
$$;

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.service_categories ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.specialist_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.venue_profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_services ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.portfolio_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.provider_blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.favorites ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.conversation_members ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.blocks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;

-- The mobile clients subscribe to messages. Without this publication an INSERT
-- succeeds but other connected clients only see it after a manual reload.
ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;

CREATE POLICY profiles_read ON public.profiles FOR SELECT USING (NOT is_banned OR id = auth.uid() OR public.is_admin());
CREATE POLICY profiles_update_own ON public.profiles FOR UPDATE USING (id = auth.uid()) WITH CHECK (id = auth.uid() AND NOT is_banned);
CREATE POLICY catalog_categories_read ON public.service_categories FOR SELECT USING (is_active OR public.is_admin());
CREATE POLICY catalog_services_read ON public.services FOR SELECT USING (is_active OR public.is_admin());
CREATE POLICY specialist_profiles_read ON public.specialist_profiles FOR SELECT USING (TRUE);
CREATE POLICY specialist_profiles_write ON public.specialist_profiles FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY venue_profiles_read ON public.venue_profiles FOR SELECT USING (TRUE);
CREATE POLICY venue_profiles_write ON public.venue_profiles FOR ALL USING (id = auth.uid()) WITH CHECK (id = auth.uid());
CREATE POLICY provider_services_read ON public.provider_services FOR SELECT USING (TRUE);
CREATE POLICY provider_services_write ON public.provider_services FOR ALL USING (provider_id = auth.uid()) WITH CHECK (provider_id = auth.uid());
CREATE POLICY portfolio_read ON public.portfolio_items FOR SELECT USING (NOT is_hidden OR owner_id = auth.uid() OR public.is_admin());
CREATE POLICY portfolio_write ON public.portfolio_items FOR ALL USING (owner_id = auth.uid()) WITH CHECK (owner_id = auth.uid());
CREATE POLICY bookings_read ON public.bookings FOR SELECT USING (client_id = auth.uid() OR provider_id = auth.uid() OR public.is_admin());
CREATE POLICY blocks_owner ON public.provider_blocks FOR ALL USING (provider_id = auth.uid()) WITH CHECK (provider_id = auth.uid());
CREATE POLICY reviews_read ON public.reviews FOR SELECT USING (NOT is_hidden OR client_id = auth.uid() OR public.is_admin());
CREATE POLICY reviews_insert ON public.reviews FOR INSERT WITH CHECK (
  client_id = auth.uid() AND EXISTS (
    SELECT 1 FROM public.bookings b
    WHERE b.id = booking_id AND b.client_id = auth.uid() AND b.provider_id = target_id AND b.status = 'completed'
  )
);
CREATE POLICY favorites_owner ON public.favorites FOR ALL USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY conversations_read ON public.conversations FOR SELECT USING (
  kind = 'category' OR public.is_conversation_member(id)
);
CREATE POLICY members_read ON public.conversation_members FOR SELECT USING (
  user_id = auth.uid() OR public.is_conversation_member(conversation_id)
);
CREATE POLICY messages_read ON public.messages FOR SELECT USING (
  (NOT is_hidden OR sender_id = auth.uid() OR public.is_admin()) AND EXISTS (
    SELECT 1 FROM public.conversations c
    WHERE c.id = conversation_id AND (
      c.kind = 'category' OR public.is_conversation_member(c.id)
    )
  )
);
CREATE POLICY messages_insert ON public.messages FOR INSERT WITH CHECK (
  sender_id = auth.uid()
  AND EXISTS (
    SELECT 1 FROM public.conversations c
    WHERE c.id = conversation_id AND (
      c.kind = 'category'
      OR public.is_conversation_member(c.id)
    )
  )
  AND NOT EXISTS (
    SELECT 1
    FROM public.conversations direct
    JOIN public.conversation_members other ON other.conversation_id = direct.id
    JOIN public.blocks b ON
      (b.blocker_id = auth.uid() AND b.blocked_id = other.user_id)
      OR (b.blocker_id = other.user_id AND b.blocked_id = auth.uid())
    WHERE direct.id = conversation_id
      AND direct.kind = 'direct'
      AND other.user_id <> auth.uid()
  )
);
CREATE POLICY notifications_owner ON public.notifications FOR SELECT USING (user_id = auth.uid());
CREATE POLICY notifications_update_owner ON public.notifications FOR UPDATE USING (user_id = auth.uid()) WITH CHECK (user_id = auth.uid());
CREATE POLICY user_blocks_owner ON public.blocks FOR ALL USING (blocker_id = auth.uid()) WITH CHECK (blocker_id = auth.uid());
CREATE POLICY reports_insert ON public.reports FOR INSERT WITH CHECK (reporter_id = auth.uid());
CREATE POLICY reports_read ON public.reports FOR SELECT USING (reporter_id = auth.uid() OR public.is_admin());
CREATE POLICY reports_admin_update ON public.reports FOR UPDATE USING (public.is_admin()) WITH CHECK (public.is_admin());
CREATE POLICY audit_admin_read ON public.audit_logs FOR SELECT USING (public.is_admin());

REVOKE ALL ON FUNCTION public.is_admin() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.handle_new_user() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.touch_updated_at() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_appointment(UUID, BIGINT, TIMESTAMPTZ, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.create_stay_booking(UUID, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.transition_booking(UUID, public.booking_status) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_provider_unavailable_intervals(UUID, TIMESTAMPTZ, TIMESTAMPTZ) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.admin_set_user_banned(UUID, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.set_initial_role(public.account_role, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_or_create_direct_conversation(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_chats() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.mark_conversation_read(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.register_device_token(TEXT, TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.unregister_device_token(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_my_private_profile() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_my_private_profile(TEXT) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_venue_location(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.update_my_venue_location(DOUBLE PRECISION, DOUBLE PRECISION, BOOLEAN) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.consume_ai_quota() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.get_push_tokens(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.notify_booking_change() FROM PUBLIC;
REVOKE ALL ON FUNCTION public.search_providers(public.provider_type, TEXT, TEXT, TEXT, NUMERIC, TEXT, DOUBLE PRECISION, DOUBLE PRECISION) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.is_conversation_member(UUID) FROM PUBLIC;
REVOKE ALL ON FUNCTION public.moderate_report(UUID, TEXT, TEXT) FROM PUBLIC;

GRANT USAGE ON SCHEMA public TO anon, authenticated;
GRANT SELECT ON public.service_categories, public.services TO anon, authenticated;
GRANT SELECT ON public.provider_search_view TO authenticated;
GRANT SELECT ON public.profiles, public.specialist_profiles, public.venue_profiles, public.provider_services, public.portfolio_items, public.reviews TO authenticated;
GRANT SELECT, UPDATE ON public.notifications TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.favorites, public.provider_blocks, public.blocks TO authenticated;
GRANT SELECT, INSERT ON public.messages, public.reports TO authenticated;
GRANT SELECT ON public.conversations, public.conversation_members, public.bookings TO authenticated;
GRANT UPDATE(full_name, avatar_url, city) ON public.profiles TO authenticated;
GRANT INSERT, UPDATE, DELETE ON public.specialist_profiles, public.venue_profiles, public.provider_services, public.portfolio_items TO authenticated;
GRANT INSERT ON public.reviews TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated;
GRANT EXECUTE ON FUNCTION public.create_appointment(UUID, BIGINT, TIMESTAMPTZ, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.create_stay_booking(UUID, TIMESTAMPTZ, TIMESTAMPTZ, INTEGER, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.transition_booking(UUID, public.booking_status) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_provider_unavailable_intervals(UUID, TIMESTAMPTZ, TIMESTAMPTZ) TO authenticated;
GRANT EXECUTE ON FUNCTION public.admin_set_user_banned(UUID, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.set_initial_role(public.account_role, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_or_create_direct_conversation(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_chats() TO authenticated;
GRANT EXECUTE ON FUNCTION public.mark_conversation_read(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.search_providers(public.provider_type, TEXT, TEXT, TEXT, NUMERIC, TEXT, DOUBLE PRECISION, DOUBLE PRECISION) TO authenticated;
GRANT EXECUTE ON FUNCTION public.is_conversation_member(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.moderate_report(UUID, TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_push_tokens(UUID) TO service_role;
GRANT EXECUTE ON FUNCTION public.register_device_token(TEXT, TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.unregister_device_token(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_my_private_profile() TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_my_private_profile(TEXT) TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_venue_location(UUID) TO authenticated;
GRANT EXECUTE ON FUNCTION public.update_my_venue_location(DOUBLE PRECISION, DOUBLE PRECISION, BOOLEAN) TO authenticated;
GRANT EXECUTE ON FUNCTION public.consume_ai_quota() TO authenticated;
GRANT EXECUTE ON FUNCTION public.get_push_tokens(UUID) TO service_role;

INSERT INTO storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
VALUES
  ('avatars', 'avatars', TRUE, 10485760, ARRAY['image/jpeg', 'image/png', 'image/webp']),
  ('portfolio', 'portfolio', TRUE, 52428800, ARRAY['image/jpeg', 'image/png', 'image/webp', 'video/mp4', 'video/quicktime']),
  ('legal', 'legal', TRUE, 1048576, ARRAY['text/html'])
ON CONFLICT (id) DO UPDATE SET
  public = EXCLUDED.public,
  file_size_limit = EXCLUDED.file_size_limit,
  allowed_mime_types = EXCLUDED.allowed_mime_types;

CREATE POLICY media_public_read ON storage.objects FOR SELECT USING (bucket_id IN ('avatars', 'portfolio'));
CREATE POLICY media_owner_insert ON storage.objects FOR INSERT TO authenticated
WITH CHECK (bucket_id IN ('avatars', 'portfolio') AND (storage.foldername(name))[1] = auth.uid()::TEXT);
CREATE POLICY media_owner_update ON storage.objects FOR UPDATE TO authenticated
USING ((storage.foldername(name))[1] = auth.uid()::TEXT)
WITH CHECK ((storage.foldername(name))[1] = auth.uid()::TEXT);
CREATE POLICY media_owner_delete ON storage.objects FOR DELETE TO authenticated
USING ((storage.foldername(name))[1] = auth.uid()::TEXT);
